language: go

sudo: false

cache:
  directories:
  - node_modules

go:
- 1.2.2
- 1.3.3
- 1.4
- 1.5.4
- 1.6.2
- master

env: pip_install="pip install --user"

matrix:
  allow_failures:
  - go: master
  include:
  - go: 1.6.2
    os: osx
    env: pip_install="sudo pip install"

before_script:
- $pip_install flake8
- go get github.com/urfave/gfmxr/...
- go get golang.org/x/tools/cmd/goimports
- if [ ! -f node_modules/.bin/markdown-toc ] ; then
    npm install markdown-toc ;
  fi
- go get github.com/urfave/gfmxr/...
- mkdir -p ${GOPATH%%:*}/src/gopkg.in/urfave
- rm -rvf ${GOPATH%%:*}/src/gopkg.in/urfave/cli.v2
- rm -rvf ${GOPATH%%:*}/pkg/*/gopkg.in/urfave/cli.v2.a
- ln -sv ${TRAVIS_BUILD_DIR} ${GOPATH%%:*}/src/gopkg.in/urfave/cli.v2

script:
- flake8 runtests cli-v1-to-v2
- ./runtests gen
- ./runtests vet
- ./runtests test
- ./runtests gfmxr
- ./cli-v1-to-v2 --selftest
- ./runtests migrations
- ./runtests toc
